<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['password_policies_account_lockout'] = 'Account Lockout';
$lang['password_policies_app_description'] = 'The Password Policy app is used to fine tune user password policy rules.  This enforces passwords that meet your criteria and helps to make your system more secure.';
$lang['password_policies_app_name'] = 'Политика паролей';
$lang['password_policies_history_size'] = 'Размер истории';
$lang['password_policies_maximum_password_age'] = 'Максимальный срок действия пароля';
$lang['password_policies_minimum_password_age'] = 'Минимальный срок действия пароля';
$lang['password_policies_minimum_password_length'] = 'Минимальная длина пароля';
$lang['password_policies_modify_any_time'] = 'Изменить любое время';
$lang['password_policies_no_expire'] = 'Не истикает';
$lang['password_policies_no_history'] = 'Без истории';
