<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['password_policies_account_lockout'] = 'Blokada konta';
$lang['password_policies_app_description'] = 'Aplikacja reguł haseł używana jest do sprawnego zarządzania hasłami użytkowników.  Wymusza ona hasła, które spełniają Twoje kryteria i pomagają utrzymać system bezpiecznym.';
$lang['password_policies_app_name'] = 'Reguły haseł';
$lang['password_policies_history_size'] = 'Rozmiar historii';
$lang['password_policies_maximum_password_age'] = 'Maksymalny wiek hasła';
$lang['password_policies_minimum_password_age'] = 'Minimalny wiek hasła';
$lang['password_policies_minimum_password_length'] = 'Minimalna siła hasła';
$lang['password_policies_modify_any_time'] = 'Modyfikacja w dowolnym momencie';
$lang['password_policies_no_expire'] = 'Nie wygasa';
$lang['password_policies_no_history'] = 'Brak historii';
